In [7]:
import torch
import numpy as np
import torch.nn as nn


In [8]:
# Task 1.1
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n{x_data}\n")

np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n{x_np}\n")

x_ones = torch.ones_like(x_data)
print(f"Ones Tensor:\n{x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n{x_rand}\n")

print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Tensor từ list:
tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
tensor([[1, 2],
        [3, 4]])

Ones Tensor:
tensor([[1, 1],
        [1, 1]])

Random Tensor:
tensor([[0.1559, 0.3650],
        [0.3390, 0.0559]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


In [9]:
# Task 1.2
print("\n--- Task 1.2 ---")
print("Cộng x_data với chính nó:\n", x_data + x_data)
print("Nhân x_data với 5:\n", x_data * 5)
print("Nhân ma trận x_data với x_data.T:\n", x_data @ x_data.T)



--- Task 1.2 ---
Cộng x_data với chính nó:
 tensor([[2, 4],
        [6, 8]])
Nhân x_data với 5:
 tensor([[ 5, 10],
        [15, 20]])
Nhân ma trận x_data với x_data.T:
 tensor([[ 5, 11],
        [11, 25]])


In [10]:
# Task 1.3
print("\n--- Task 1.3 ---")
print("Hàng đầu tiên:", x_data[0])
print("Cột thứ hai:", x_data[:, 1])
print("Giá trị ở hàng 2, cột 2:", x_data[1, 1].item())


--- Task 1.3 ---
Hàng đầu tiên: tensor([1, 2])
Cột thứ hai: tensor([2, 4])
Giá trị ở hàng 2, cột 2: 4


In [11]:
# Task 1.4
print("\n--- Task 1.4 ---")
x = torch.rand(4, 4)
print("Tensor ban đầu:\n", x)
reshaped = x.view(16, 1)
print("Tensor sau khi reshape (16,1):\n", reshaped)


--- Task 1.4 ---
Tensor ban đầu:
 tensor([[2.3535e-01, 1.8425e-02, 5.6709e-01, 8.0068e-01],
        [9.3871e-02, 3.9538e-01, 4.8098e-01, 1.1030e-01],
        [4.2417e-01, 2.1708e-01, 5.1025e-01, 8.0031e-01],
        [3.8326e-05, 4.5608e-01, 5.6245e-01, 7.8385e-01]])
Tensor sau khi reshape (16,1):
 tensor([[2.3535e-01],
        [1.8425e-02],
        [5.6709e-01],
        [8.0068e-01],
        [9.3871e-02],
        [3.9538e-01],
        [4.8098e-01],
        [1.1030e-01],
        [4.2417e-01],
        [2.1708e-01],
        [5.1025e-01],
        [8.0031e-01],
        [3.8326e-05],
        [4.5608e-01],
        [5.6245e-01],
        [7.8385e-01]])


In [12]:
# Task 2.1
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

y = x + 2
print(f"y: {y}")
print(f"grad_fn của y: {y.grad_fn}")

z = y * y * 3
print(f"z: {z}")

z.backward()
print(f"Đạo hàm của z theo x: {x.grad}")


x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x7d1d74fa9ff0>
z: tensor([27.], grad_fn=<MulBackward0>)
Đạo hàm của z theo x: tensor([18.])


In [13]:
# Task 3.1

linear_layer = nn.Linear(in_features=5, out_features=2)

input_tensor = torch.randn(3, 5)

output = linear_layer(input_tensor)

print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n{output}")


Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
tensor([[ 0.4040,  0.8632],
        [ 0.7676,  0.0659],
        [ 0.1379, -0.7504]], grad_fn=<AddmmBackward0>)


In [14]:
# Task 3.2


embedding_layer = nn.Embedding(num_embeddings=10, embedding_dim=3)

input_indices = torch.LongTensor([1, 5, 0, 8])

embeddings = embedding_layer(input_indices)

print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n{embeddings}")


Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
tensor([[-1.5215,  0.8262, -0.7119],
        [ 1.5344,  1.8520,  0.2176],
        [ 1.4323, -1.2654,  0.7386],
        [ 0.5282,  0.8513, -1.2538]], grad_fn=<EmbeddingBackward0>)


In [15]:
# Task 3.3


class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU()
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, indices):
        embeds = self.embedding(indices)
        hidden = self.activation(self.linear(embeds))
        output = self.output_layer(hidden)
        return output

# Khởi tạo mô hình và kiểm tra đầu ra
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([[1, 2, 5, 9]])  # một câu gồm 4 từ
output_data = model(input_data)

print(f"Model output shape: {output_data.shape}")
print(f"Output:\n{output_data}")


Model output shape: torch.Size([1, 4, 2])
Output:
tensor([[[-0.2994, -0.2680],
         [-0.0880, -0.3452],
         [ 0.1581, -0.8496],
         [ 0.1813, -0.2096]]], grad_fn=<ViewBackward0>)
